version: '3.7'

services:
# Mongodb service
  db:
    image: mongo:latest
    container_name: mongo_api_platform
    volumes:
      - mongo_data:/data/db

# Node.js Express App
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    ports:
      - 5051:5051
    environment:
      - BACKEND_URL=http://localhost:5051
      - PORT=5051
      - MONGODB_URL=mongodb://db:27017/urlshortener?serverSelectionTimeoutMS=3000&directConnection=true
    depends_on:
      - db

volumes:
  mongo_data: {}